# Generated by Django 3.2.8 on 2021-12-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsdreamIT', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
